AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: Bucket name
  VersioningState:
    Type: String
    AllowedValues: [Enabled, Suspended]
    Default: Enabled

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningState
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: Environment
          Value: Production
        - Key: Owner
          Value: alice@example.com

Outputs:
  BucketName:
    Value: !Ref MyBucket
